add better ci and readme

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,18 +7,104 @@ on:
     branches: [ master ]
   workflow_dispatch:
 
+env:
+  CARGO_TERM_COLOR: always
+  FOUNDRY_PROFILE: ci
+
 jobs:
-  build:
+  frontend:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
+      - name: Checkout code
+        uses: actions/checkout@v6
 
-      - uses: actions/setup-node@v4
+      - name: Install Node.Js
+        uses: actions/setup-node@v6
         with:
           node-version: 24.x
 
-      - run: |
+      - name: Install dependencies
+        run: |
           yarn install
+
+      - name: Build frontend
+        run: |
           cp .env.test .env
           yarn run build
+
+  rust-contracts:
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        contract:
+          - announcer
+          - registry
+
+    steps:
+      - name: Checkout code of ${{ matrix.contract }}
+        uses: actions/checkout@v6
+
+      - name: Install Rust
+        uses: dsherret/rust-toolchain-file@v1
+
+      - name: Install Binaryen
+        run: |
+          sudo wget -c https://github.com/WebAssembly/binaryen/releases/download/$BINARYEN_VERSION/binaryen-$BINARYEN_VERSION-x86_64-linux.tar.gz -O - | sudo tar -xz -C .
+          sudo cp binaryen-$BINARYEN_VERSION/bin/wasm-opt /usr/bin/
+        env:
+          BINARYEN_VERSION: version_126
+
+      - name: Cargo cache
+        uses: Swatinem/rust-cache@v2
+
+      - name: Cargo fmt
+        run: cargo fmt -- --check
+        working-directory: ./contracts/${{ matrix.contract }}
+
+      - name: Cargo clippy
+        run: cargo clippy --release --all-targets -- -D warnings
+        working-directory: ./contracts/${{ matrix.contract }}
+
+      - name: Cargo build
+        run: cargo build --release
+        working-directory: ./contracts/${{ matrix.contract }}
+
+      - name: Cargo test
+        run: cargo test --release
+        working-directory: ./contracts/${{ matrix.contract }}
+
+      - name: Check client files
+        run: |
+          CLIENT_RS_FILE="client/src/${{ matrix.contract }}_client.rs"
+          test -f $CLIENT_RS_FILE && git diff --exit-code $CLIENT_RS_FILE || (echo "$CLIENT_RS_FILE missing or modified" && exit 1)
+          CLIENT_IDL_FILE="client/${{ matrix.contract }}_client.idl"
+          test -f $CLIENT_IDL_FILE && git diff --exit-code $CLIENT_IDL_FILE || (echo "$CLIENT_IDL_FILE missing or modified" && exit 1)
+        working-directory: ./contracts/${{ matrix.contract }}
+
+  solidity-contracts:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          submodules: recursive
+
+      - name: Install Foundry
+        uses: foundry-rs/foundry-toolchain@v1
+
+      - name: Show Forge version
+        run: forge --version
+
+      - name: Run Forge fmt
+        run: forge fmt --check
+        working-directory: ./contracts/beer-market
+
+      - name: Run Forge build
+        run: forge build --sizes
+        working-directory: ./contracts/beer-market
+
+      - name: Run Forge tests
+        run: forge test -vvv
+        working-directory: ./contracts/beer-market
